word_list = [
    'americanah',
    'ratos',
    'uma vida pequena',
    'eu sou malala',
    'o dia do curinga',
    'a garota das laranjas',
    'pessoas normais',
    'a vida invisivel de euridice gusmao',
    'a elegancia do ourico',
    'farenheit 451',
    'a redoma de vidro',
    'uma mente inquieta',
    'no escuro',
    'a resposta',
    'demian',
    'o sol e para todos',
    'hibisco roxo',
    'eu sou a lenda',
    'quatro estacoes',
    'cada das estrelas',
    'os testamentos',
    'um outro brooklyn',
    'a metamorfose',
    'clube da luta',
    'a revolucao dos bichos',
    'o mundo de sofia',
    'o sol na cabeca',
    'o quarto de giovanni',
    'quem tem medo do feminismo negro',
    'estacao carandiru',
    'prisioneiras',
    'carcereiros',
    'dias perfeitos',
    'grandes esperancas',
    'doze anos de escravidao',
    'pelos olhos da morte',
    'primeiro amor',
    'a vida que ninguem ve',
    'capitaes da areia',
    'enclausurado',
    'a maquina de fazer espanhois',
    'o apocalipse dos trabalhadores',
    'o filho de mil homens',
    'admiravel mundo novo',
    'a cor do leite',
    'os sofrimentos do jovem werther',
    'uma mente inquieta',
    'o feminismo e para todo mundo',
    'farmacia literaria',
    'o mito da beleza',
    'sidarta',
    'a peste',
    'o estrangeiro',
    'anarquista gracas a deus',
    'cem anos de solidao',
    'angustia',
    'a cor purpura',
    'o castelo de vidro',
    'tampa',
    'o conto da aia',
    'onze minutos',
    'lacos de familia',
    'a hora da estrela',
    'casa das estrelas',
    'e isto um homem',
    'um amor incomodo',
    'boy erased',
    'bela maldade'
]
